"""Exact conditional GRF sampling given the Haar coarse projection, then exponentiate.

The Gaussian layer G is a stationary periodic GRF generated by Fourier coloring:
G = ifft2(fft2(white) * amp).real with radially symmetric real amp (so the product is
Hermitian and G exactly real). Then Cov(G) is the circulant operator with spectrum
S(k) = amp(k)^2:   Sigma v = ifft2(fft2(v) * S).real.

Conditioning target: the level-l orthonormal-Haar approximation cA_l, which for Haar
with periodization equals P_l G = 2^l * blockmean_{2^l}(G) — a LINEAR map. Exact
conditional sampling of G | P_l G = c* uses the Hoffman–Ribak construction

    G_cond = G~ + Sigma P^T M^{-1} (c* - P G~),        M = P Sigma P^T,

with G~ a fresh unconditional draw. M is stationary under coarse-grid translations
(Sigma stationary, P commutes with block shifts), hence circulant on the coarse grid:
M^{-1} is a coarse-grid FFT solve with the numerically-precomputed spectrum. The DC
mode of M is exactly 0 (S(0)=0 -> zero-mean fields) and the residual's DC is 0 by
construction; the solve uses a pseudo-inverse that zeroes numerically-null modes.

Exactness is validated in tests_p2/test_sandbox_conditional.py against dense linear
algebra on a small grid (conditional mean and covariance, machine/statistical
tolerance) plus a machine-precision constraint-reproduction check at 128^2.

The lognormal layer is pointwise: L = exp(sigma_g * G - sigma_g^2/2) - 1 (zero-mean,
scaledrift's convention). NOTE the log map does not commute with coarse-graining:
conditional ensembles here fix the GAUSSIAN coarse c_G, not the Haar coarse of L
itself (which varies slightly across redraws). All Stage-A truth values are therefore
computed at the ESTIMAND level (statistics of the exact joint law, from pooled exact
samples); the per-coarse ensembles additionally provide variance-reduced conditional
structure. This subtlety is pre-declared in the Stage-A log.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np


# ----------------------------------------------------------------------------- GRF --

@dataclass
class GRFSpec:
    """Frozen recipe for the Gaussian layer: P(k) ~ k^-alpha, unit pixel variance."""
    shape: tuple = (128, 128)
    alpha: float = 2.0
    _amp: np.ndarray = field(default=None, repr=False, compare=False)

    def amp(self):
        """Fourier amplitude A(k), scaled so Var(G_pixel) = 1 analytically."""
        if self._amp is None:
            ky = np.fft.fftfreq(self.shape[0])[:, None]
            kx = np.fft.fftfreq(self.shape[1])[None, :]
            k = np.sqrt(ky ** 2 + kx ** 2)
            k[0, 0] = np.inf                       # DC killed -> zero-mean field
            a = k ** (-self.alpha / 2.0)
            npix = self.shape[0] * self.shape[1]
            pixvar = float(np.sum(a ** 2)) / npix   # Var(G_i) = (1/N) sum_k S(k)
            self._amp = a / np.sqrt(pixvar)
        return self._amp

    def spectrum(self):
        """S(k) = A(k)^2, the covariance operator's spectrum."""
        a = self.amp()
        return a * a


def sample_grf(spec: GRFSpec, rng: np.random.Generator):
    """One unconditional draw of the Gaussian layer (exactly N(0, Sigma))."""
    white = rng.standard_normal(spec.shape)
    return np.fft.ifft2(np.fft.fft2(white) * spec.amp()).real


def sigma_apply(v, spec: GRFSpec):
    """Sigma v (circulant covariance operator)."""
    return np.fft.ifft2(np.fft.fft2(v) * spec.spectrum()).real


# ------------------------------------------------------------- Haar coarse (linear) --

def haar_coarse(v, lvl: int):
    """Level-`lvl` orthonormal Haar approximation: 2^lvl * blockmean over 2^lvl blocks.

    Equals pywt.wavedec2(v, 'haar', mode='periodization', level=lvl)[0] exactly
    (cross-checked in tests where pywt is available).
    """
    b = 2 ** lvl
    H, W = v.shape
    return v.reshape(H // b, b, W // b, b).mean(axis=(1, 3)) * (2.0 ** lvl)


def haar_coarse_adjoint(u, lvl: int):
    """Adjoint P^T: distribute each coarse value over its block, scaled 2^-lvl."""
    b = 2 ** lvl
    return np.repeat(np.repeat(u, b, axis=0), b, axis=1) * (2.0 ** (-lvl))


# --------------------------------------------------------- coarse-grid solve for M --

def coarse_spectrum(spec: GRFSpec, lvl: int):
    """DFT eigenvalues of M = P Sigma P^T on the coarse grid (numerically exact).

    M is circulant under coarse translations; its first column is M(delta_0), and the
    eigenvalues are the 2D FFT of that column. Symmetric kernel -> real eigenvalues.
    """
    Hc = spec.shape[0] // 2 ** lvl
    Wc = spec.shape[1] // 2 ** lvl
    delta = np.zeros((Hc, Wc))
    delta[0, 0] = 1.0
    col = haar_coarse(sigma_apply(haar_coarse_adjoint(delta, lvl), spec), lvl)
    lam = np.fft.fft2(col)
    assert np.max(np.abs(lam.imag)) < 1e-8 * np.max(np.abs(lam.real))
    return lam.real


def _pinv_solve(r, lam):
    """M^{-1} r via coarse-grid FFT; numerically-null modes (incl. DC) zeroed."""
    lam_inv = np.where(lam > 1e-12 * lam.max(), 1.0 / np.where(lam == 0, 1.0, lam), 0.0)
    return np.fft.ifft2(np.fft.fft2(r) * lam_inv).real


# --------------------------------------------------------------- conditional draws --

def conditional_mean_map(c_star, spec: GRFSpec, lvl: int, lam=None):
    """E[G | P_lvl G = c*] = Sigma P^T M^{-1} c* (exact, deterministic)."""
    if lam is None:
        lam = coarse_spectrum(spec, lvl)
    u = _pinv_solve(c_star, lam)
    return sigma_apply(haar_coarse_adjoint(u, lvl), spec)


def conditional_redraw(c_star, spec: GRFSpec, lvl: int, rng: np.random.Generator,
                       lam=None):
    """One exact sample of G | (haar_coarse(G, lvl) = c*), Hoffman–Ribak."""
    if lam is None:
        lam = coarse_spectrum(spec, lvl)
    g_tilde = sample_grf(spec, rng)
    resid = c_star - haar_coarse(g_tilde, lvl)
    u = _pinv_solve(resid, lam)
    return g_tilde + sigma_apply(haar_coarse_adjoint(u, lvl), spec)


# ------------------------------------------------------------------ lognormal layer --

def lognormal_map(g, sigma_g: float):
    """Zero-mean lognormal: exp(sigma*g - sigma^2/2) - 1 (scaledrift convention)."""
    return np.exp(sigma_g * g - 0.5 * sigma_g ** 2) - 1.0
