"""t1-t4 validation of the colored heavy-tailed base (R38 L1; JAX gate).

Validates the COMMITTED frozen filter artifact (results_p2/
l1_filter_gowerstreet.npz) + the JAX sampler, synthetics only:
  t1 spectrum : post-map annular spectrum matches the frozen target within
                tolerance on well-sampled rings (both filter sources);
  t2 marginals: unit variance + q95/q99/q999 match unit-variance t(5)
                (analytic refs 1.5608 / 2.6064 / 4.5650) within a few %;
  t3 D4      : the filter map is EXACTLY invariant under all 8 group
                elements (ring-lookup construction), and per-sample ring
                spectra are invariant under the field action;
  t4 repro   : same PRNG key -> identical samples.
"""
import os
import sys

import numpy as np

import jax

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "scripts_p2"))

from colored_base import colored_t_base, ring_spectrum, ring_table  # noqa: E402

ART = np.load(os.path.join(REPO, "results_p2", "l1_filter_gowerstreet.npz"))
Z, X = ART["z_grid"], ART["x_grid"]
T5_Q = {0.95: 1.5608, 0.99: 2.6064, 0.999: 4.5650}


def _sample(filt, n=256, key=0):
    x = colored_t_base(jax.random.PRNGKey(key), (n, 64, 64, 1), filt, Z, X)
    return np.asarray(x)[..., 0]


def test_t1_spectrum_matches_frozen_target():
    rings = ring_table(64)
    counts = np.array([(rings == r).sum() for r in range(rings.max() + 1)])
    sel = counts >= 16
    for src in ("oct1", "oct2rescaled"):
        x = _sample(ART[f"filt_{src}"], key=1)
        got = ring_spectrum(x)
        tgt = ART[f"target_{src}"]
        got_n = got / got[counts > 0].mean()
        tgt_n = tgt / tgt[counts > 0].mean()
        dev = np.abs(got_n[sel] - tgt_n[sel]) / np.maximum(tgt_n[sel], 1e-12)
        assert dev.max() < 0.06, f"{src}: spectrum dev {dev.max():.3f}"


def test_t2_marginals_are_unit_t5():
    x = _sample(ART["filt_oct1"], n=512, key=2).ravel()
    assert abs(x.std() - 1.0) < 0.02, f"std {x.std():.3f}"
    assert abs(x.mean()) < 0.01
    for q, ref in T5_Q.items():
        emp = np.quantile(x, q)
        assert abs(emp - ref) / ref < 0.05, f"q{q}: {emp:.3f} vs {ref}"
        emp_l = -np.quantile(x, 1 - q)
        assert abs(emp_l - ref) / ref < 0.05, f"lower q{q}: {emp_l:.3f}"


def test_t3_filter_and_law_d4_invariant():
    # The field-space D4 action is, in frequency space, generated by
    # kx -> -kx, ky -> -ky, and kx <-> ky. On the fftfreq index layout
    # these are the index maps below (NOT array rot90/flips — a first
    # version of this test used matrix flips, which scramble the fftfreq
    # ordering, and failed on a correct filter; corrected pre-use).
    N = ART["filt_oct1"].shape[0]
    neg = (-np.arange(N)) % N
    for src in ("oct1", "oct2rescaled"):
        filt = ART[f"filt_{src}"]
        assert np.array_equal(filt[neg, :], filt), f"{src}: kx->-kx"
        assert np.array_equal(filt[:, neg], filt), f"{src}: ky->-ky"
        assert np.array_equal(filt.T, filt), f"{src}: kx<->ky"
        assert np.array_equal(filt[neg, :].T[:, neg], filt), f"{src}: comp"
    x = _sample(ART["filt_oct1"], n=8, key=3)
    s0 = np.array([ring_spectrum(f[None]) for f in x])
    for g in (lambda f: np.rot90(f, 1), lambda f: f[::-1]):
        sg = np.array([ring_spectrum(g(f)[None]) for f in x])
        assert np.allclose(sg, s0, rtol=1e-9), "per-sample spectra not invariant"


def test_t4_seeded_reproducibility():
    a = _sample(ART["filt_oct1"], n=4, key=7)
    b = _sample(ART["filt_oct1"], n=4, key=7)
    c = _sample(ART["filt_oct1"], n=4, key=8)
    assert np.array_equal(a, b)
    assert not np.array_equal(a, c)
