"""Synthetic fields for the control ladder and the in-test GRF null gate.

* ``powerlaw_grf`` -- isotropic power-law Gaussian random field, P(k) ~ k^-alpha.
  Generated by coloring white noise in Fourier space, so it is exactly periodic
  (matches ``mode="periodization"``) and, for a pure power law, self-similar: after
  per-octave normalization its wavelet statistics are scale-invariant -> the null.
* ``lognormal_field`` -- pointwise exp of a GRF: known non-Gaussianity, an analytic
  control where scale-drift is expected.
"""
from __future__ import annotations

import numpy as np


def _radial_k(shape):
    ky = np.fft.fftfreq(shape[0])[:, None]
    kx = np.fft.fftfreq(shape[1])[None, :]
    return np.sqrt(ky ** 2 + kx ** 2)


def powerlaw_grf(shape, alpha, rng, normalize=True):
    """Real isotropic GRF with power spectrum P(k) proportional to k**(-alpha).

    DC mode set to zero (zero-mean field). ``rng`` is a numpy Generator.
    """
    k = _radial_k(shape)
    k[0, 0] = np.inf              # kill DC -> zero mean, no divergence
    amp = k ** (-alpha / 2.0)     # amplitude ~ sqrt(P)
    white = rng.standard_normal(shape)
    field = np.fft.ifft2(np.fft.fft2(white) * amp).real
    if normalize:
        field = (field - field.mean()) / field.std()
    return field


def lognormal_field(shape, alpha, sigma, rng, normalize=False):
    """Zero-mean lognormal field: exp(sigma*g - sigma^2/2) - 1 for a unit-var GRF g.

    ``sigma`` sets the non-Gaussianity (skewness grows with sigma). Larger sigma =>
    stronger scale-drift of the conditional statistics.
    """
    g = powerlaw_grf(shape, alpha, rng, normalize=True)
    f = np.exp(sigma * g - 0.5 * sigma ** 2) - 1.0
    if normalize:
        f = (f - f.mean()) / f.std()
    return f
